### ISSUE TITLE
'senza create' errors in ubuntu 14.04 after upgrade to senza 0.84

### ISSUE THREAD

**Issue by csenol** [zalando-stups/senza#127]
Hi

I upgraded to senza 0.84 but  now having following errors whenever I try to create a simple app with a yaml file
I use ubuntu 14.04
```
Traceback (most recent call last):
  File "/usr/local/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 1138, in main
    handle_exceptions(cli)()
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 229, in wrapper
    func()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 517, in create
    data = create_cf_template(definition, region, version, parameter, force)
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 553, in create_cf_template
    data = evaluate(definition.copy(), args, account_info, force)
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 210, in evaluate
    componentfn = get_component(componenttype)
  File "/usr/local/lib/python3.4/dist-packages/senza/components/__init__.py", line 13, in get_component
    module = importlib.import_module('{}.components.{}'.format(root_package, module_name))
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/senza/components/taupage_auto_scaling_group.py", line 3, in <module>
    import pierone.api
  File "/usr/local/lib/python3.4/dist-packages/pierone/api.py", line 8, in <module>
    from zign.api import get_named_token, get_existing_token
  File "/usr/local/lib/python3.4/dist-packages/zign/api.py", line 3, in <module>
    import keyring
  File "/usr/local/lib/python3.4/dist-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/local/lib/python3.4/dist-packages/keyring/core.py", line 13, in <module>
    from . import backend
  File "/usr/local/lib/python3.4/dist-packages/keyring/backend.py", line 16, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 29, in <module>
    import symbol
  File "/usr/lib/python3.4/symbol.py", line 98, in <module>
    for _name, _value in list(globals().items()):
RuntimeError: dictionary changed size during iteration
```

**Comment by csenol** [comment]
Temporary solution

sudo pip3 uninstall stups-senza
sudo pip3 install -I stups-senza==0.78

**Comment by csenol** [comment]
I fixed this issue by explicitly specifying python version

Instead of "senza create  hello.yaml v1 latest"
Now I use "python3 -m senza create hello.yaml v1 latest"

I don't know why this one is working. I would be happy if a python expert can explain it =)

PS: Prior to senza==0.80 I didn't have any issue
