### ISSUE TITLE
senza --piu flag does not work

### ISSUE THREAD

**Issue by valgog** [zalando-stups/senza#136]
When issuing `senza instances zmon-worker --piu "reproduce senza piu bug"`, the following exception happens: 

```
Stack Name │Ver.│Resource ID│Instance ID│Public IP│Private IP    │State  │LB Status│Launched
zmon-worker 1    AppWorker   i-d220d26b            172.31.166.240 RUNNING            18h ago
Traceback (most recent call last):
  File "/usr/local/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 1313, in main
    handle_exceptions(cli)()
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 248, in wrapper
    func()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 908, in instances
    call(['piu', 'request-access', row['private_ip'], '{} via senza'.format(piu), '-O', odd_host])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1479, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by hjacobs** [comment]
hmm, actually I wasn't even aware of the "--piu" feature (probably @tuxlife implemented it) --- I don't like having feature creep, so maybe I will even remove it :smiling_imp:
