### ISSUE TITLE
Allow referencing SenzaInfo in default Arguments parameter values

### ISSUE THREAD

**Issue by vosmann** [zalando-stups/senza#145]
Having
```yaml
Parameters:
  - ClusterName:
  - Description: "The name of the Cassandra cluster."
  - Default: "{{SenzaInfo.StackVersion}}"
```
in a Senza yaml file results in:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pystache/context.py", line 282, in get
    result = self._get_simple(parts[0])
  File "/usr/local/lib/python3.5/site-packages/pystache/context.py", line 315, in _get_simple
    raise KeyNotFoundError(name, "part missing")
pystache.context.KeyNotFoundError: Key 'SenzaInfo' not found: part missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 1316, in main
    handle_exceptions(cli)()
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 248, in wrapper
    func()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  <snip>
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 616, in print_cfjson
    data = create_cf_template(definition, region, version, parameter, force)
  <snip>
  File "/usr/local/lib/python3.5/site-packages/pystache/renderer.py", line 454, in render
    return self._render_string(template, *context, **kwargs)
  <snip>
  File "/usr/local/lib/python3.5/site-packages/pystache/renderengine.py", line 182, in render
    return parsed_template.render(self, context_stack)
  <snip>
  File "/usr/local/lib/python3.5/site-packages/pystache/context.py", line 284, in get
    raise KeyNotFoundError(name, "first part")
pystache.context.KeyNotFoundError: Key 'SenzaInfo.StackVersion' not found: first part
```

Not sure if it's possible with Pystache, since it's referencing a parameter before all of them have been parsed, but it would be nice if we could reference `SenzaInfo` params in definitions of `Arguments` params.

**Comment by hjacobs** [comment]
Yes, I agree --- seems to be reasonable feature request (or bug report?)

**Comment by vosmann** [comment]
A gentle feature request, I'd call it :)

**Comment by CVirus** [comment]
+1 for this

**Comment by CVirus** [comment]
Same for:
``` yaml
SenzaInfo:
  StackName: cassandra-{{SenzaInfo.StackVersion}}
```
Errors with:

```
pystache.context.KeyNotFoundError: Key 'SenzaInfo.StackVersion' not found: missing 'StackVersion'

**Comment by hjacobs** [comment]
@CVirus your case does not really make sense for me: why would you want the stack version in the stack name? This would lead to having the stack version twice in the AWS Cloud Formation identifiers...

**Comment by CVirus** [comment]
Because I'm using the StackVersion as either "staging" or "live" so if I have ```StackName: cassandra``` and then I have a a loadbalancer with ```Type: Senza::WeightedDnsElasticLoadBalancer```.. I see 2 entries created in my Route53 records cassandra.lounge.zalan.do and cassandra-staging.lounge.zalan.do

**Comment by hjacobs** [comment]
@CVirus the better alternative IMHO would be to change the `WeightedDnsElasticLoadBalancer` settings, see http://docs.stups.io/en/latest/components/senza.html#senza-weighteddnselasticloadbalancer

**Comment by CVirus** [comment]
@hjacobs I didn't know about that .. Thanks a lot :-)
