### ISSUE TITLE
Senza scale confused about earlier stack version

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/senza#158]
First, if I try senza `scale` command like this:
```
$ senza scale osm-tile-server-v10 10
```
--- nothing happens.  No diagnostic message is produced, no actions taken on an ASG.  If I try it like this:
```
$ senza scale osm-tile-server 10
Scaling osm-tile-server-v10-AppServer-171MBBBFW8W86 from 5 to 10 instances.. OK
Traceback (most recent call last):
  File "/home/oshulgin/.local/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/home/oshulgin/.local/lib/python3.5/site-packages/senza/cli.py", line 1381, in main
    handle_exceptions(cli)()
  File "/home/oshulgin/.local/lib/python3.5/site-packages/senza/cli.py", line 248, in wrapper
    func()
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/senza/cli.py", line 1301, in scale
    group = get_auto_scaling_group(asg, asg_name)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/senza/respawn.py", line 16, in get_auto_scaling_group
    raise Exception('Auto Scaling Group {} not found'.format(asg_name))
Exception: Auto Scaling Group osm-tile-server-v9-AppServer-1HY0YKCD3YYBZ not found
```
It first detects the correct stack version (the only one that is not deleted at the moment), then it is confused about some older ASG of this stack (it is long deleted).

**Comment by a1exsh** [comment]
But looks like even though it has error'd out in the latter invokation, it did act on the v10 ASG...
