### ISSUE TITLE
resolve_security_groups does not work with non-default-vpc

### ISSUE THREAD

**Issue by kenden** [zalando-stups/senza#160]
When there is no default security group, running sensa to update a stack causes an error:
```
$senza init myapp.yaml --region "eu-west-1"
```
---> creates the stack, no problem. But if we run this again...
```
senza init myapp.yaml --region "eu-west-1"

Please select the project template
1) bgapp: Background app with single EC2 instance
2) postgresapp: HA Postgres app, which needs an S3 bucket to store WAL files
3) rediscluster: Elasticache cluster running multiple redis nodes, with replication / HA
4) redisnode: Elasticache node running redis, without replication / HA (for caching)
5) webapp: HTTP app with auto scaling, ELB and DNS
Please select (1-5) [5]:
Application ID [hello-world]:
Docker image without tag/version (e.g. "pierone.example.org/myteam/myapp") [stups/hello-world]:
HTTP port [8080]:
HTTP health check path [/]:
EC2 instance type [t2.micro]:
Did you need OAuth-Credentials from Mint? [y/N]:
Please select the load balancer scheme
1) internal: only accessible from the own VPC
2) internet-facing: accessible from the public internet
Please select (1-2) [1]:
DEBUG: in check_security_group(): sg_name app-hello-world
Checking security group app-hello-world.. EXCEPTION OCCURRED: An error occurred (InvalidParameterValue) when calling the DescribeSecurityGroups operation: Invalid value 'app-hello-world' for groupName. You may not reference Amazon VPC security groups by name. Please use the corresponding id for this operation.
Traceback (most recent call last):
  File "/Users/edited/senza/venv/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/senza/cli.py", line 1383, in main
    handle_exceptions(cli)()
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/senza/cli.py", line 250, in wrapper
    func()
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/senza/cli.py", line 808, in init
    variables = module.gather_user_variables(variables, region, account_info)
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/senza/templates/webapp.py", line 79, in gather_user_variables
    rules_missing = check_security_group(sg_name, [('tcp', 22), ('tcp', http_port)], region, allow_from_self=True)
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/senza/templates/_helper.py", line 63, in check_security_group
    sg = get_security_group(region, sg_name)
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/senza/aws.py", line 12, in get_security_group
    return list(ec2.security_groups.filter(GroupNames=[sg_name]))[0]
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/boto3/resources/collection.py", line 161, in pages
    pages = [getattr(client, self._py_operation_name)(**params)]
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/edited/senza/venv/lib/python3.5/site-packages/botocore/client.py", line 396, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the DescribeSecurityGroups operation: Invalid value 'app-hello-world' for groupName. You may not reference Amazon VPC security groups by name. Please use the corresponding id for this operation.

**Comment by tuxlife** [comment]
:+1:

**Comment by kenden** [comment]
fixed. Closing.
