### ISSUE TITLE
error when switching traffic across regions

### ISSUE THREAD

**Issue by alnkpa** [zalando-stups/senza#186]
Hi,

when trying to switch traffic for a stack deployed on multiple regions I get the following error:

```
Calculating new weights.. OK
Stack Name   │Version│Identifier           │Old Weight%│Delta │Compensation│New Weight%│Current
service         service-black         100.0 -100.0                      0.0         
service schwarz service-schwarz         0.0  100.0                    100.0 <       
Traceback (most recent call last):
  File "/usr/local/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 1360, in main
    handle_exceptions(cli)()
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 248, in wrapper
    func()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 1043, in traffic
    change_version_traffic(ref, percentage, region)
  File "/usr/local/lib/python3.4/dist-packages/senza/traffic.py", line 374, in change_version_traffic
    inform_sns(arns, message, region)
  File "/usr/local/lib/python3.4/dist-packages/senza/traffic.py", line 383, in inform_sns
    sns.publish(TopicArn=sns_topic, Subject="SenzaTrafficRedirect", Message=jsonizer.encode((message)))
  File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 395, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: TopicArn
```

What could be wrong here?

**Comment by alnkpa** [comment]
Updating fixed it.
