### ISSUE TITLE
Senza weird behaviour after deleting some stacks with traffic

### ISSUE THREAD

**Issue by Cesarla** [zalando-stups/senza#194]
If a stack is deleted without reassigning its traffic, sometime the version disappears:
```
senza traffic --region eu-west-1 foo-service-app
Error: Missing argument "stack_name".
Stack Name      │Version   │Identifier                    │Weight%
foo-service-app            foo-service-app-c967f52wad       10.0
foo-service-app            foo-service-app-c967f52WITHAD     5.0
foo-service-app 0404withAD foo-service-app-0404withAD       85.0
foo-service-app WADc967f52 foo-service-app-WADc967f52        0.0
```
If I try to take out the pre-assign traffic, senza complains that the stack doesn't exist.
```
senza traffic --region eu-west-1 foo-service-app c967f52wad 0
Usage: senza traffic [OPTIONS] STACK_NAME [STACK_VERSION] [PERCENTAGE]

Error: Stack version c967f52wad found
```
If I try to assign traffic to a new stack with no traffic, It crashes:
```
senza traffic --region eu-west-1 foo-service-app WADc967f52 10
Calculating new weights.. EXCEPTION OCCURRED: 'foo-service-app-c967f52wad'
Traceback (most recent call last):
  File "/usr/local/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 1402, in main
    handle_exceptions(cli)()
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 252, in wrapper
    func()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 1064, in traffic
    change_version_traffic(ref, percentage, region)
  File "/usr/local/lib/python3.5/site-packages/senza/traffic.py", line 364, in change_version_traffic
    new_record_weights, partial_count, percentage, identifier_versions)
  File "/usr/local/lib/python3.5/site-packages/senza/traffic.py", line 83, in compensate
    for i in sorted(new_record_weights.keys(), key=lambda x: identifier_versions[x], reverse=True):
  File "/usr/local/lib/python3.5/site-packages/senza/traffic.py", line 83, in <lambda>
    for i in sorted(new_record_weights.keys(), key=lambda x: identifier_versions[x], reverse=True):
KeyError: 'foo-service-app-c967f52wad'
```
... but success if a put all traffic to a instance with some traffic
```
senza traffic --region eu-west-1 foo-service-app 0404withAD 100
Calculating new weights.. OK
Stack Name      │Version   │Identifier                    │Old Weight%│Delta│Compensation│New Weight%│Current
foo-service-app            foo-service-app-c967f52WITHAD         5.0  -5.0                      0.0
foo-service-app            foo-service-app-c967f52wad           10.0 -10.0                      0.0
foo-service-app 0404withAD foo-service-app-0404withAD           85.0  15.0                    100.0 <
foo-service-app WADc967f52 foo-service-app-WADc967f52            0.0                            0.0
```
The "ghosts" :ghost: stacks disappear after the last step:
```
senza traffic --region eu-west-1 foo-service-app WADc967f52 10
Calculating new weights.. OK
Stack Name      │Version   │Identifier                 │Old Weight%│Delta│Compensation│New Weight%│Current
foo-service-app 0404withAD foo-service-app-0404withAD       100.0 -10.0                     90.0
foo-service-app WADc967f52 foo-service-app-WADc967f52         0.0  10.0                     10.0 <
```

**Comment by hjacobs** [comment]
Hmm, the "KeyError" stack trace definitely indicates a bug.
