### ISSUE TITLE
improve the validation of the region in command senza status/wait/events/resources...

### ISSUE THREAD

**Issue by kenden** [zalando-stups/senza#233]
calling
`$ senza status --region senza-stack-template.yml stack1`
or
`$ senza wait --region minion-stack-template.yml stack1`
or
`senza events --region minion-stack-template.yml stack1`
...
(notice I forgot the region)
results in:
```
Unknown Error.
Please create an issue with the content of /var/folders/90/pz80sxl93gl11zjsbmylwmxj42vx03/T/senza-traceback-giep3cgd

cat /var/folders/90/pz80sxl93gl11zjsbmylwmxj42vx03/T/senza-traceback-giep3cgd
Traceback (most recent call last):
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/senza/error_handling.py", line 35, in wrapper
    func()
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/senza/cli.py", line 934, in status
    for stack in sorted(get_stacks(stack_refs, region)):
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/senza/aws.py", line 236, in get_stacks
    results = cf.list_stacks(**kwargs)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/client.py", line 262, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/client.py", line 541, in _make_api_call
    operation_model, request_dict)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 274, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 314, in __call__
    caught_exception)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/user/dev/project1/deploy/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 356, in _check_caught_exception
    raise caught_exception
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://cloudformation.senza-stack-template.yml.amazonaws.com/"
```

Maybe check against a list of valid region names?

**Comment by hjacobs** [comment]
Released in https://github.com/zalando-stups/senza/releases/tag/1.0.69
