### ISSUE TITLE
Improve error message when using unquoted Senza variables

### ISSUE THREAD

**Issue by kenden** [zalando-stups/senza#236]
When using Senza variables, if one forgets to surround the varialbe with quotes, ex:
```
Value: {{SenzaInfo.StackName}}
```
then a message like this is displayed when calling, for ex, `senza update`
```
Unknown Error.
  Please create an issue with the content of /var/folders/90/pz80sxl93gl11zjsbmylwmxj42vx03/T/senza-traceback-_bv0iaac
```
That file contains:
```
$ cat /var/folders/90/pz80sxl93gl11zjsbmylwmxj42vx03/T/senza-traceback-dqad4jpx
Traceback (most recent call last):
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/senza/error_handling.py", line 35, in wrapper
    func()
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 1058, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 1390, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 1359, in full_process_value
    value = self.process_value(ctx, value)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 1349, in process_value
    return self.type_cast_value(ctx, value)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 1338, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/core.py", line 1336, in _convert
    return self.type(value, self, ctx)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/senza/cli.py", line 126, in convert
    data = yaml.safe_load(response.read())
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/user/dev/project/deploy/.venv/lib/python3.5/site-packages/yaml/constructor.py", line 128, in construct_mapping
    "found unhashable key", key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
  in "<byte string>", line 174, column 18:
              Value: {{SenzaInfo.StackName}}
                     ^
found unhashable key
  in "<byte string>", line 174, column 19:
              Value: {{SenzaInfo.StackName}}
                      ^
```

It is not obvious from that error what the problem is.
Changing the template to quote the senza variable solves the issue:
```
Value: "{{SenzaInfo.StackName}}"
```

The strange thing is that
```
Value: my-cool-stack-name
```
works fine, and my-cool-stack-name has no quotes here.

## Expected behavior:
No error when using
```
Value: {{SenzaInfo.StackName}}
```

or at least a more helpful message like:
```
Error parsing template file my_senza_template.yml
Found unhashable key line 174, column 19:
              Value: {{SenzaInfo.StackName}}
                      ^
Senza variables should be double quoted, ex: "{{SenzaInfo.StackName}}"
```

I got bitten by this issue enough times to report a bug.

**Comment by hjacobs** [comment]
@kenden I think that's expected YAML behavior as curly braces ("{") are valid YAML syntax for mappings (JSON dict/object).

**Comment by hjacobs** [comment]
(YAML parsing is done before doing the template variable substitutes)

**Comment by kenden** [comment]
@hjacobs thanks!
Would it make sense to do the YAML parsing after the variable substitution?
Maybe the substitution could result in incorrect YAML?
