### ISSUE TITLE
Error "Unknown Error: 'Weight'"

### ISSUE THREAD

**Issue by dborovikov** [zalando-stups/senza#252]
I run `senza traffic <stack>` and get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/senza/error_handling.py", line 65, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 1073, in traffic
    print_version_traffic(ref, region)
  File "/usr/local/lib/python3.5/site-packages/senza/traffic.py", line 302, in print_version_traffic
    identifier_versions.keys())
  File "/usr/local/lib/python3.5/site-packages/senza/traffic.py", line 27, in get_weights
    if r['Weight']:
KeyError: 'Weight'
```

```
senza --version
Senza 1.0.79
```

**Comment by hjacobs** [comment]
@dborovikov that looks like a bug.

Can you show the output of `senza dump <your-stack>` here? (remove sensitive information in the output)

**Comment by dborovikov** [comment]
```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Exhibitor Ie Dev (HostedZone: ie.zalan.do., ScalyrAccountKey: 0z1e6W38e7SrUNpw5jklqLhms/W_haOJfAFyk_YhqQTM-, DockerBaseImage: registry.opensource.zalan.do/acid/exhibitor, DockerVersion: 3.4-p5, ApplicationID: exhibitor-ie-dev, ExhibitorBucket: zalando-stups-mint-xxx-eu-central-1/exhibitor-ie-dev)",
    "Mappings": {
        "Images": {
            "eu-central-1": {
                "LatestTaupageImage": "ami-d1806ebe"
            }
        },
        "LoadBalancerInternalSubnets": {
            "eu-central-1": {
                "Subnets": [
                    "subnet-ddc21bb4",
                    "subnet-9558a1ee"
                ]
            }
        },
        "LoadBalancerSubnets": {
            "eu-central-1": {
                "Subnets": [
                    "subnet-dac21bb3",
                    "subnet-9658a1ed"
                ]
            }
        },
        "Senza": {
            "Info": {
                "Parameters": [
                    {
                        "DockerVersion": {
                            "Description": "Docker image version of exhibitor."
                        }
                    },
                    {
                        "DockerBaseImage": {
                            "Default": "registry.opensource.zalan.do/acid/exhibitor",
                            "Description": "Docker image path of exhibitor."
                        }
                    },
                    {
                        "HostedZone": {
                            "Description": "AWS Hosted Zone to work with"
                        }
                    },
                    {
                        "ExhibitorBucket": {
                            "Default": "zalando-stups-mint-xxx-eu-central-1/exhibitor-ie-dev",
                            "Description": "S3 bucket for exhibitor (to store shared configuration and backups)"
                        }
                    },
                    {
                        "ScalyrAccountKey": {
                            "Default": "",
                            "Description": "Scalyr account key"
                        }
                    },
                    {
                        "ApplicationID": {
                            "Default": "exhibitor",
                            "Description": "The Application Id which got registered for lawang in Yourturn/Kio."
                        }
                    }
                ],
                "StackName": "exhibitor-ie-dev",
                "StackVersion": "blue",
                "Tags": [
                    {
                        "Name": "exhibitor-ie-dev-blue"
                    },
                    {
                        "StackVersion": "blue"
                    },
                    {
                        "StackName": "exhibitor-ie-dev"
                    }
                ]
            }
        },
        "ServerSubnets": {
            "eu-central-1": {
                "Subnets": [
                    "subnet-ddc21bb4",
                    "subnet-9558a1ee"
                ]
            }
        }
    },
    "Parameters": {
        "ApplicationID": {
            "Default": "exhibitor",
            "Description": "The Application Id which got registered for lawang in Yourturn/Kio.",
            "Type": "String"
        },
        "DockerBaseImage": {
            "Default": "registry.opensource.zalan.do/acid/exhibitor",
            "Description": "Docker image path of exhibitor.",
            "Type": "String"
        },
        "DockerVersion": {
            "Description": "Docker image version of exhibitor.",
            "Type": "String"
        },
        "ExhibitorBucket": {
            "Default": "zalando-stups-mint-xxx-eu-central-1/exhibitor-ie-dev",
            "Description": "S3 bucket for exhibitor (to store shared configuration and backups)",
            "Type": "String"
        },
        "HostedZone": {
            "Description": "AWS Hosted Zone to work with",
            "Type": "String"
        },
        "ScalyrAccountKey": {
            "Default": "",
            "Description": "Scalyr account key",
            "Type": "String"
        }
    },
    "Resources": {
        "AppServer": {
            "CreationPolicy": {
                "ResourceSignal": {
                    "Count": "1",
                    "Timeout": "PT15M"
                }
            },
            "Properties": {
                "DesiredCapacity": 3,
                "HealthCheckGracePeriod": 300,
                "HealthCheckType": "ELB",
                "LaunchConfigurationName": {
                    "Ref": "AppServerConfig"
                },
                "LoadBalancerNames": [
                    {
                        "Ref": "ExhibitorLoadBalancer"
                    }
                ],
                "MaxSize": 3,
                "MinSize": 3,
                "Tags": [
                    {
                        "Key": "Name",
                        "PropagateAtLaunch": true,
                        "Value": "exhibitor-ie-dev-blue"
                    },
                    {
                        "Key": "StackName",
                        "PropagateAtLaunch": true,
                        "Value": "exhibitor-ie-dev"
                    },
                    {
                        "Key": "StackVersion",
                        "PropagateAtLaunch": true,
                        "Value": "blue"
                    }
                ],
                "VPCZoneIdentifier": {
                    "Fn::FindInMap": [
                        "ServerSubnets",
                        {
                            "Ref": "AWS::Region"
                        },
                        "Subnets"
                    ]
                }
            },
            "Type": "AWS::AutoScaling::AutoScalingGroup"
        },
        "AppServerConfig": {
            "Properties": {
                "AssociatePublicIpAddress": false,
                "EbsOptimized": false,
                "IamInstanceProfile": {
                    "Ref": "AppServerInstanceProfile"
                },
                "ImageId": {
                    "Fn::FindInMap": [
                        "Images",
                        {
                            "Ref": "AWS::Region"
                        },
                        "LatestTaupageImage"
                    ]
                },
                "InstanceType": "t2.micro",
                "SecurityGroups": [
                    {
                        "Fn::GetAtt": [
                            "ExhibitorSecurityGroup",
                            "GroupId"
                        ]
                    }
                ],
                "UserData": {
                    "Fn::Base64": "#taupage-ami-config\napplication_id: exhibitor-ie-dev\napplication_logrotate_rotate: 4\napplication_logrotate_size: 100M\napplication_version: 3.4-p5\nenvironment:\n  S3_BUCKET: zalando-stups-mint-xxx-eu-central-1/exhibitor-ie-dev\n  S3_PREFIX: blue\nnotify_cfn:\n  resource: AppServer\n  stack: exhibitor-ie-dev-blue\nports:\n  2181: 2181\n  2888: 2888\n  3888: 3888\n  8181: 8181\nroot: true\nruntime: Docker\nscalyr_account_key: \nsource: registry.opensource.zalan.do/acid/exhibitor:3.4-p5\n"
                }
            },
            "Type": "AWS::AutoScaling::LaunchConfiguration"
        },
        "AppServerInstanceProfile": {
            "Properties": {
                "Path": "/",
                "Roles": [
                    {
                        "Ref": "ExhibitorRole"
                    }
                ]
            },
            "Type": "AWS::IAM::InstanceProfile"
        },
        "AppServerScaleDown": {
            "Properties": {
                "AdjustmentType": "ChangeInCapacity",
                "AutoScalingGroupName": {
                    "Ref": "AppServer"
                },
                "Cooldown": "60",
                "ScalingAdjustment": "-1"
            },
            "Type": "AWS::AutoScaling::ScalingPolicy"
        },
        "AppServerScaleUp": {
            "Properties": {
                "AdjustmentType": "ChangeInCapacity",
                "AutoScalingGroupName": {
                    "Ref": "AppServer"
                },
                "Cooldown": "60",
                "ScalingAdjustment": "1"
            },
            "Type": "AWS::AutoScaling::ScalingPolicy"
        },
        "ExhibitorLoadBalancer": {
            "Properties": {
                "CrossZone": true,
                "HealthCheck": {
                    "HealthyThreshold": 3,
                    "Interval": 30,
                    "Target": "HTTP:8181/exhibitor/v1/cluster/state",
                    "Timeout": 5,
                    "UnhealthyThreshold": 5
                },
                "Listeners": [
                    {
                        "InstancePort": 8181,
                        "LoadBalancerPort": 8181,
                        "Protocol": "TCP"
                    }
                ],
                "LoadBalancerName": "exhibitor-blue",
                "Scheme": "internal",
                "SecurityGroups": [
                    {
                        "Fn::GetAtt": [
                            "ExhibitorSecurityGroup",
                            "GroupId"
                        ]
                    }
                ],
                "Subnets": {
                    "Fn::FindInMap": [
                        "LoadBalancerSubnets",
                        {
                            "Ref": "AWS::Region"
                        },
                        "Subnets"
                    ]
                }
            },
            "Type": "AWS::ElasticLoadBalancing::LoadBalancer"
        },
        "ExhibitorRole": {
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Statement": [
                        {
                            "Action": "sts:AssumeRole",
                            "Effect": "Allow",
                            "Principal": {
                                "Service": "ec2.amazonaws.com"
                            }
                        }
                    ],
                    "Version": "2012-10-17"
                },
                "Path": "/",
                "Policies": [
                    {
                        "PolicyDocument": {
                            "Statement": [
                                {
                                    "Action": "s3:*",
                                    "Effect": "Allow",
                                    "Resource": [
                                        "arn:aws:s3:::zalando-stups-mint-xxx-eu-central-1/exhibitor-ie-dev",
                                        "arn:aws:s3:::zalando-stups-mint-xxx-eu-central-1/exhibitor-ie-dev/*"
                                    ]
                                }
                            ],
                            "Version": "2012-10-17"
                        },
                        "PolicyName": "S3Access"
                    }
                ]
            },
            "Type": "AWS::IAM::Role"
        },
        "ExhibitorRoute53Record": {
            "Properties": {
                "HostedZoneName": "ie.zalan.do.",
                "Name": "exhibitor-ie-dev-blue.ie.zalan.do.",
                "ResourceRecords": [
                    {
                        "Fn::GetAtt": [
                            "ExhibitorLoadBalancer",
                            "DNSName"
                        ]
                    }
                ],
                "TTL": 20,
                "Type": "CNAME"
            },
            "Type": "AWS::Route53::RecordSet"
        },
        "ExhibitorSecurityGroup": {
            "Properties": {
                "GroupDescription": "Exhibitor Appliance Security Group",
                "SecurityGroupIngress": [
                    {
                        "CidrIp": "0.0.0.0/0",
                        "FromPort": 22,
                        "IpProtocol": "tcp",
                        "ToPort": 22
                    },
                    {
                        "CidrIp": "0.0.0.0/0",
                        "FromPort": 2181,
                        "IpProtocol": "tcp",
                        "ToPort": 2181
                    },
                    {
                        "CidrIp": "0.0.0.0/0",
                        "FromPort": 2888,
                        "IpProtocol": "tcp",
                        "ToPort": 2888
                    },
                    {
                        "CidrIp": "0.0.0.0/0",
                        "FromPort": 3888,
                        "IpProtocol": "tcp",
                        "ToPort": 3888
                    },
                    {
                        "CidrIp": "0.0.0.0/0",
                        "FromPort": 8181,
                        "IpProtocol": "tcp",
                        "ToPort": 8181
                    },
                    {
                        "CidrIp": "0.0.0.0/0",
                        "FromPort": 9100,
                        "IpProtocol": "tcp",
                        "ToPort": 9100
                    }
                ]
            },
            "Type": "AWS::EC2::SecurityGroup"
        }
    }
}
```

**Comment by dborovikov** [comment]
@hjacobs I suspect problem is that https://github.com/zalando-incubator/exhibitor-appliance doesn't create main DNS record for a stack, it creates DNS record only for a version.
