### ISSUE TITLE
Error while running domains subcommand

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando-stups/senza#267]
When I run:
```
senza domains --region eu-central-1 -o json hello-bus --stacktrace-visible
```
This happens:
```
Traceback (most recent call last):
  File "/Users/rcaricio/.virtualenvs/stups-tools/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/senza/cli.py", line 1486, in main
    HandleExceptions(cli)()
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/senza/error_handling.py", line 89, in __call__
    self.die_unknown_error(e)
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/senza/error_handling.py", line 54, in die_unknown_error
    raise e
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/senza/error_handling.py", line 66, in __call__
    self.function(*args, **kwargs)
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/rcaricio/.virtualenvs/stups-tools/lib/python3.5/site-packages/senza/cli.py", line 1048, in domains
    'value': ','.join([r['Value'] for r in record.get('ResourceRecords')])})
TypeError: 'NoneType' object is not iterable
```

**Comment by rafaelcaricio** [comment]
This is due development tests in Senza. Closing it.
