### ISSUE TITLE
Can't Deploy ZMON appliance (without SSL Certificate)

### ISSUE THREAD

**Issue by priesus** [zalando-stups/senza#277]
Senza is returning an error, when I'm trying to deploy the ZMON appliance: 

```
senza --region=eu-central-1 create zmon-appliance-planetexpress-qa.yaml cd14c1 cd14
Generating Cloud Formation template.. EXCEPTION OCCURRED: An error occurred (ValidationError) when calling the GetServerCertificate operation: The specified value for serverCertificateName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-
Unknown Error: An error occurred (ValidationError) when calling the GetServerCertificate operation: The specified value for serverCertificateName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-.
Please create an issue with the content of /var/folders/cv/08715ldx7qx_76kkn3kmdmdnlc10w4/T/senza-traceback-l_pvs53y
```

Contents of this file are the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/senza/manaus/iam.py", line 80, in get_by_name
    certificate = certificates[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/senza/error_handling.py", line 69, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 555, in create
    data = create_cf_template(definition, region, version, parameter, force, parameter_file)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 638, in create_cf_template
    data = evaluate(definition.copy(), args, account_info, force)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 239, in evaluate
    definition = componentfn(definition, configuration, args, info, force, account_info)
  File "/usr/local/lib/python3.5/site-packages/senza/components/elastic_load_balancer.py", line 67, in component_elastic_load_balancer
    certificate = IAMServerCertificate.get_by_name(ssl_cert)
  File "/usr/local/lib/python3.5/site-packages/senza/manaus/iam.py", line 82, in get_by_name
    raise error
  File "/usr/local/lib/python3.5/site-packages/senza/manaus/iam.py", line 71, in get_by_name
    response = client.get_server_certificate(ServerCertificateName=name)
  File "/usr/local/lib/python3.5/site-packages/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.5/site-packages/botocore/client.py", line 572, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the GetServerCertificate operation: The specified value for serverCertificateName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-`
```

The LB-part of zmon-appliance-planetexpress-qa.yaml (autogenerated by Stups' script) looks like this:

```
    ZmonApplianceLoadBalancer:
      Type: Senza::ElasticLoadBalancer
      HTTPPort: 9090
      HealthCheckPath: /health
      HealthCheckPort: 9090
      SecurityGroups:
          app-zmon-{{AccountInfo.TeamID}}
      Scheme: internal
      SSLCertificateId: arn:none # hack to disable SSL
      Listeners:
        LoadBalancerPort: 9090
        Protocol: HTTP
        InstancePort: 9090
        InstanceProtocol: HTTP
```

(had to remove the '-' signs for Markup to work).

Am I right to assume SSLCertificateId: arn:none is causing the issue?
What can I do?

**Comment by hjacobs** [comment]
@priesus I will check this --- apparently the latest Senza version (changing SSL certificate selection) is breaking the "hack" to disable SSL.

**Comment by hjacobs** [comment]
Solution: SSL certs should be ignored if "Listeners" is set manually in Senza definition.

**Comment by hjacobs** [comment]
@priesus fixed in https://github.com/zalando-stups/senza/releases/tag/1.0.89
