### ISSUE TITLE
ELB.from_boto_dict KeyError for internal load balancers

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#293]
```
$ senza create myapp.yaml cd123 cd123c1
Generating Cloud Formation template.. EXCEPTION OCCURRED: 'CanonicalHostedZoneName'
Unknown Error: 'CanonicalHostedZoneName'.
Please create an issue with the content of /tmp/senza-traceback-jmufgixh
$ cat /tmp/senza-traceback-jmufgixh
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/senza/error_handling.py", line 70, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/senza/cli.py", line 528, in create
    data = create_cf_template(definition, region, version, parameter, force, parameter_file)
  File "/usr/local/lib/python3.5/dist-packages/senza/cli.py", line 611, in create_cf_template
    data = evaluate(definition.copy(), args, account_info, force)
  File "/usr/local/lib/python3.5/dist-packages/senza/cli.py", line 234, in evaluate
    definition = componentfn(definition, configuration, args, info, force, account_info)
  File "/usr/local/lib/python3.5/dist-packages/senza/components/weighted_dns_elastic_load_balancer.py", line 29, in component_weighted_dns_elastic_load_balancer
    return component_elastic_load_balancer(definition, configuration, args, info, force, account_info)
  File "/usr/local/lib/python3.5/dist-packages/senza/components/elastic_load_balancer.py", line 99, in component_elastic_load_balancer
    convert_domain_records_to_alias(domain_name)
  File "/usr/local/lib/python3.5/dist-packages/senza/manaus/route53.py", line 360, in convert_domain_records_to_alias
    alias_record = record.to_alias()
  File "/usr/local/lib/python3.5/dist-packages/senza/manaus/route53.py", line 280, in to_alias
    elb = ELB.get_by_dns_name(dns_name)
  File "/usr/local/lib/python3.5/dist-packages/senza/manaus/elb.py", line 172, in get_by_dns_name
    return cls.from_boto_dict(load_balancer)
  File "/usr/local/lib/python3.5/dist-packages/senza/manaus/elb.py", line 139, in from_boto_dict
    hosted_zone_name = load_balancer['CanonicalHostedZoneName']
KeyError: 'CanonicalHostedZoneName'

**Comment by hjacobs** [comment]
Just for reference my ELB configuration in Senza (note that it's using an internal ELB with HTTP-only):
```
- AppLoadBalancer:
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      HealthCheckPath: /api/v1/health/check
      SecurityGroups:
        - app-foobar-lb
      Scheme: internal
      Listeners:
      - LoadBalancerPort: 8080
        Protocol: HTTP
        InstancePort: 8080
        InstanceProtocol: HTTP
