### ISSUE TITLE
Conversion of NS records to Alias is still not implemented

### ISSUE THREAD

**Issue by taojang** [zalando-stups/senza#314]
Senza Version: 2.0.109

When I run the following command
```
senza create --dry-run production.yaml blah cd12
```

I get the following error

```
Traceback (most recent call last):
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/senza/error_handling.py", line 71, in __call__
    self.function(*args, **kwargs)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/click/core.py", line 86, in augment_usage_errors
    yield
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/senza/cli.py", line 606, in create
    data = create_cf_template(definition, region, version, parameter, force, parameter_file)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/senza/cli.py", line 689, in create_cf_template
    data = evaluate(definition.copy(), args, account_info, force)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/senza/cli.py", line 241, in evaluate
    definition = componentfn(definition, configuration, args, info, force, account_info)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/senza/components/weighted_dns_elastic_load_balancer.py", line 29, in component_weighted_dns_elastic_load_balancer
    return component_elastic_load_balancer(definition, configuration, args, info, force, account_info)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/senza/components/elastic_load_balancer.py", line 99, in component_elastic_load_balancer
    convert_domain_records_to_alias(domain_name)
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/senza/manaus/route53.py", line 371, in convert_domain_records_to_alias
    alias_record = record.to_alias()
  File "/home/tyang/machinery/zalando-py/lib/python3.5/site-packages/senza/manaus/route53.py", line 307, in to_alias
    "still not implemented".format(self.type))
NotImplementedError: Conversion of NS records to Alias is still not implemented
```

**Comment by harti2006** [comment]
The problem is, that senza assumes a DNS structure like `{SUBDOMAIN}.{HOSTED_ZONE}` (e.g. `my-app.example.org`) at many places, which was completely right for the "old" CNAME records.

Now with the "alias" feature, it is possible to have A records with name={HOSTED_ZONE} (just `example.org`), but `senza create` fails to produce the correct Cloud Formation template, e.g. when setting the name of a WeightedDnsElasticLoadBalancer equal to the hosted zone name (e.g. `MainDomain: example.org`).

However we managed to create the records with pure cloud formation:

```yaml
Resources:
  AppLoadBalancerMainDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - AppLoadBalancer
            - DNSName
        HostedZoneId:
          Fn::GetAtt:
            - AppLoadBalancer
            - CanonicalHostedZoneNameID
      HostedZoneName: example.org.
      Name: example.org.
      SetIdentifier: "example.org-{{SenzaInfo.StackVersion}}"
      Type: A
      Weight: 0
  AppLoadBalancerVersionDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - AppLoadBalancer
            - DNSName
        HostedZoneId:
          Fn::GetAtt:
            - AppLoadBalancer
            - CanonicalHostedZoneNameID
      HostedZoneName: example.org.
      Name: "{{SenzaInfo.StackVersion}}.example.org."
      Type: A
```

This works fine for stack creation, but later when it comes to switching the traffic using senza, it fails again 😭
