### ISSUE TITLE
Unknown Error: 'EntryPoint' object has no attribute 'resolve'.

### ISSUE THREAD

**Issue by csenol** [zalando-stups/senza#315]
I have following error with senza init

 /tmp senza --version && python --version
Senza 2.0.109
Python 3.4.3
➜  /tmp senza init test.yaml               
Unknown Error: 'EntryPoint' object has no attribute 'resolve'.
Please create an issue with the content of /tmp/senza-traceback-njipgs42
➜  /tmp cat /tmp/senza-traceback-njipgs42  
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/senza/error_handling.py", line 71, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 868, in init
    templates = get_templates()
  File "/usr/local/lib/python3.4/dist-packages/senza/templates/__init__.py", line 21, in get_templates
    module = e.resolve()
AttributeError: 'EntryPoint' object has no attribute 'resolve'

**Comment by jmcs** [comment]
You probably have an outdated version of ``setuptools``. Please upgrade it with `sudo pip install --upgrade setuptools`.

**Comment by csenol** [comment]
@jmcs That fixed my problem. Thanks a lot

**Comment by hjacobs** [comment]
for the record: "sudo pip3 install --upgrade setuptools" fixes this issue, Ubuntu 14.04 comes with setuptools v 3.3, current version is v. 30.3
