### ISSUE TITLE
Crash on referencing a non-existent yaml file

### ISSUE THREAD

**Issue by pkoryzna** [zalando-stups/senza#351]
When issuing `senza delete` or `list` command, passing a non-existent yaml file (say, when opening a new shell and forgetting to change dir, or just simple typo), senza crashes with cryptic error message: 
`Unknown Error: local variable 'ref' referenced before assignment.`

My senza version is 2.0.125.

Checking out the log file suggests it's just a missing exception handler for FileNotFound:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/senza/aws.py", line 308, in raise_file_exception
    with open(self.name) as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'some-missing-fiile.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/senza/error_handling.py", line 76, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 816, in delete
    stacks = list(get_stacks(stack_refs, region))
  File "/usr/local/lib/python3.5/site-packages/senza/aws.py", line 226, in get_stacks
    check_file_exceptions(stack_refs)
  File "/usr/local/lib/python3.5/site-packages/senza/stack_references.py", line 7, in check_file_exceptions
    stack.raise_file_exception()
  File "/usr/local/lib/python3.5/site-packages/senza/aws.py", line 312, in raise_file_exception
    raise FileError(ref, str(error))
UnboundLocalError: local variable 'ref' referenced before assignment
```

**Comment by hjacobs** [comment]
Thanks for reporting the issue!
