### ISSUE TITLE
Scale does not work anymore

### ISSUE THREAD

**Issue by Jan-M** [zalando-stups/senza#354]
```
senza scale XXX cd76c7 1
Unknown Error: 'ElasticLoadBalancing' object has no attribute 'describe_auto_scaling_groups'.
Please create an issue with the content of /tmp/senza-traceback-_kytphb0
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/senza/error_handling.py", line 76, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/senza/cli.py", line 1500, in scale
    group = get_auto_scaling_group(asg, asg_name)
  File "/usr/local/lib/python3.5/dist-packages/senza/respawn.py", line 13, in get_auto_scaling_group
    result = asg.describe_auto_scaling_groups(AutoScalingGroupNames=[asg_name])
AttributeError: 'ElasticLoadBalancing' object has no attribute 'describe_auto_scaling_groups'
```

**Comment by jmcs** [comment]
Is your boto3 updated? I can't reproduce this behaviour on my machine.

**Comment by Jan-M** [comment]
I am not sure, but why does the requirements not include a proper boto3 version then? I will check now.

**Comment by Jan-M** [comment]
>>> import boto3
>>> boto3.__version__
'1.4.0'

**Comment by jmcs** [comment]
Then that's not the issue since that's the latest version of boto, but it seems you are not using the latest version of senza version please check if it still happens in the new one.

**Comment by hjacobs** [comment]
OK, we found the issue: @Jan-M had some wrong files in `.aws/models` (imported manually for ELBv2 beta).
