### ISSUE TITLE
Unknown Error: 'PhysicalResourceId'

### ISSUE THREAD

**Issue by kdomoratski** [zalando-stups/senza#359]
I got a `senza delete` error:
Unknown Error: 'PhysicalResourceId'.
Please create an issue with the content of /tmp/senza-traceback-8ecz_cyz

****************************************senza-traceback-8ecz_cyz****************************************************
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/senza/error_handling.py", line 82, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/senza/cli.py", line 835, in delete
    for r in stack.resources:
  File "/usr/local/lib/python3.5/dist-packages/senza/manaus/cloudformation.py", line 127, in resources
    records = Route53.get_records(name=resource['PhysicalResourceId'])
KeyError: 'PhysicalResourceId'`

**Comment by jmcs** [comment]
From sentry:
    	
    resource = {
        'LastUpdatedTimestamp': datetime.datetime(...), 
        'LogicalResourceId': 'AppLoadBalancerMainDomain', 
        'ResourceStatus': 'DELETE_COMPLETE', 
        'ResourceType': 'AWS::Route53::RecordSet'
    }
