### ISSUE TITLE
Unknown Error: Conversion of MX records to Alias is still not implemented

### ISSUE THREAD

**Issue by gregdeane** [zalando-stups/senza#360]
Using: Senza 2.0.133

When trying to deploy with the latest Senza, we encountered the following:

**Unknown Error: Conversion of MX records to Alias is still not implemented.**

We have existing MX, NS, SOA, and TXT records at the domain we are deploying to, but I don't see why that should prevent the deployment.

@cjhowald Can you provide a little more insight as to what you encountered during the deploy?

**Comment by cjhowald** [comment]
### Background:

- Our live site is solutions.zalando.com
- Since our NS and SOA are at solutions.zalando.com, we could not previously deploy there or put a CNAME at that location
- Our workaround was to redirect traffic from solutions.zalando.com -> www.solutions.zalando.com via an S3 bucket, but this had [some limitations](https://github.bus.zalan.do/norris/solution-center/issues/142)
- Senza 2 appeared to have the solution with its use of A records
- For more detail and our migration plan, see [this ticket](https://github.bus.zalan.do/norris/solution-center/issues/142)

### Issue:
When attempting to deploy directly to solutions.zalando.com (for the first time) with [this configuration](https://github.bus.zalan.do/norris/norris-devops/blob/3f58e4f44e78b97430cdd06761fae6cb813adbc2/solution-center/solution-center-prod.yaml), the senza create throws the following error about our MX record at solutions.zalando.com:

**EXCEPTION OCCURRED: Conversion of MX records to Alias is still not implemented**

For testing purposes, I tried moving the MX to another domain, but then it threw the same error against our NS record, which cannot be edited. I don't see why it is attempting to convert records other than CNAME, though. Our MX, NS, SOA, and TXT records must remain at solutions.zalando.com, but should should coexist with A records just fine. Perhaps the CNAME -> A conversion code is overzealous in what it matches on?

Here is the console output:
```
./senza_deploy.sh -t 201609211256 -f solution-center/solution-center-prod.yaml
project-name: "user-service-frontend"
stack version: prod201609211256
Authenticating against https://aws.zalando.net.. OK
Assuming role AWS Account 200641888568 (zalando-norris): Shibboleth-PowerUser.. OK
Writing temporary AWS credentials.. OK
Getting OAuth2 token "pierone".. OK
Storing Docker client configuration in /Users/chowald/.docker/config.json.. OK
Creating version user-service-frontend 201609211256.. OK
creating stack prod201609211256 with ImageVersion 201609211256...
Generating Cloud Formation template..You are deploying an image that has *HIGH* severity security fixes easily available!  Please check this artifact tag in pierone and see which software versions you should upgrade to apply those fixes.
 EXCEPTION OCCURRED: Conversion of MX records to Alias is still not implemented
Unknown Error: Conversion of MX records to Alias is still not implemented.
Please create an issue with the content of /var/folders/xk/6n8tkd7560s_ltpqzwz1ndk1p8tn3_/T/senza-traceback-kkuile2e
```

And the full traceback: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/senza/error_handling.py", line 82, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 86, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 664, in create
    data = create_cf_template(definition, region, version, parameter, force, parameter_file)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 747, in create_cf_template
    data = evaluate(definition.copy(), args, account_info, force)
  File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 238, in evaluate
    definition = componentfn(definition, configuration, args, info, force, account_info)
  File "/usr/local/lib/python3.5/site-packages/senza/components/weighted_dns_elastic_load_balancer.py", line 30, in component_weighted_dns_elastic_load_balancer
    return lb_component(definition, configuration, args, info, force, account_info)
  File "/usr/local/lib/python3.5/site-packages/senza/components/elastic_load_balancer.py", line 107, in component_elastic_load_balancer
    convert_domain_records_to_alias(domain_name)
  File "/usr/local/lib/python3.5/site-packages/senza/manaus/route53.py", line 384, in convert_domain_records_to_alias
    alias_record = record.to_alias()
  File "/usr/local/lib/python3.5/site-packages/senza/manaus/route53.py", line 307, in to_alias
    "still not implemented".format(self.type))
NotImplementedError: Conversion of MX records to Alias is still not implemented
```

Note: we're using [this script](https://github.bus.zalan.do/norris/norris-devops/blob/master/senza_deploy.sh) to automate parts of our deployment while we ramp up lizzy. This doesn't seem to be part of the problem, as everything works as expected until we get to the `senza create` command.
