### ISSUE TITLE
Auto Scaling Group not found

### ISSUE THREAD

**Issue by Unisay** [zalando-stups/senza#505]
```console
$ senza patch --image latest
Patching Auto Scaling Group quala-10-AppServer-1QAODX1SBL2R5.. OK
Patching Auto Scaling Group quala-9-AppServer-1O620FA5CHPM6.. OK
Patching Auto Scaling Group quala-8-AppServer-1BAAA7CE2WDZO.. OK
Patching Auto Scaling Group quala-7-AppServer-18XLMMP669BCF.. OK
Patching Auto Scaling Group quala-6-AppServer-1TK9TEOUYLD75.. OK
Patching Auto Scaling Group quala-5-AppServer-14LKRKBKKOYRN.. OK
Patching Auto Scaling Group quala-4-AppServer-1JLNQD81Z9DE.. OK
$ senza respawn-instances --inplace
1/1 instances need to be updated in quala-10-AppServer-1QAODX1SBL2R5
Suspending scaling processes for quala-10-AppServer-1QAODX1SBL2R5.. OK
Scaling to 1 instances.. OK
Terminating old instance i-081eb5f7595a0f03c.. . . . . . . . . OK
Resetting Auto Scaling Group to original capacity (1-1-1).. OK
Resuming scaling processes for quala-10-AppServer-1QAODX1SBL2R5.. OK
Unknown Error: Auto Scaling Group quala-9-AppServer-1O620FA5CHPM6 not found.
Please create an issue with the content of /tmp/senza-traceback-zasxdjel
$ senza respawn-instances 
0/1 instances need to be updated in quala-10-AppServer-1QAODX1SBL2R5
Nothing to do
Unknown Error: Auto Scaling Group quala-9-AppServer-1O620FA5CHPM6 not found.
Please create an issue with the content of /tmp/senza-traceback-lxyhl6n5
$ cat /tmp/senza-traceback-zasxdjel
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/senza/error_handling.py", line 108, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/senza/cli.py", line 1470, in respawn_instances
    respawn_auto_scaling_group(asg_name, region, inplace=inplace, force=force)
  File "/usr/local/lib/python3.5/dist-packages/senza/respawn.py", line 136, in respawn_auto_scaling_group
    group = get_auto_scaling_group(asg, asg_name)
  File "/usr/local/lib/python3.5/dist-packages/senza/respawn.py", line 19, in get_auto_scaling_group
    raise Exception('Auto Scaling Group {} not found'.format(asg_name))
Exception: Auto Scaling Group quala-9-AppServer-1O620FA5CHPM6 not found
```

**Comment by Adeynack** [comment]
+1 on this. Here is the content of the file it suggests I include in an issue.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/senza/error_handling.py", line 108, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/senza/cli.py", line 1470, in respawn_instances
    respawn_auto_scaling_group(asg_name, region, inplace=inplace, force=force)
  File "/usr/local/lib/python3.6/site-packages/senza/respawn.py", line 136, in respawn_auto_scaling_group
    group = get_auto_scaling_group(asg, asg_name)
  File "/usr/local/lib/python3.6/site-packages/senza/respawn.py", line 19, in get_auto_scaling_group
    raise Exception('Auto Scaling Group {} not found'.format(asg_name))
Exception: Auto Scaling Group foo-bar not found
```
