### ISSUE TITLE
Senza init sometimes failes to create security groups

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/senza#57]
I got this exception several times. Not only when creating the LB security group, but also for the app security group.

Maybe there is a short waiting period needed, before newly created security groups can be used.

```
senza init hello-andre.yaml
Please select the project template
1) bgapp: Background app with single EC2 instance
2) postgresapp: HA Postgres app, which needs an S3 bucket to store WAL files
3) webapp: HTTP app with auto scaling, ELB and DNS
Please select (1-3): 3
Application ID [hello-world]: hello-andre
Docker image without tag/version (e.g. "pierone.example.org/myteam/myapp") [stups/hello-world]:
HTTP port [8080]:
HTTP health check path [/]:
EC2 instance type [t2.micro]:
Mint S3 bucket name [sensitive_data_ stripped]:
Checking security group app-hello-andre.. OK
Security group app-hello-andre does not exist. Do you want Senza to create it now? [Y/n]:
Checking security group app-hello-andre-lb.. OK
Security group app-hello-andre-lb does not exist. Do you want Senza to create it now? [Y/n]:
Traceback (most recent call last):
  File "/usr/local/bin/senza", line 9, in <module>
    load_entry_point('stups-senza==0.53', 'console_scripts', 'senza')()
  File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 798, in main
    handle_exceptions(cli)()
  File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 219, in wrapper
    func()
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 552, in init
    variables = module.gather_user_variables(variables, region)
  File "/usr/local/lib/python3.4/site-packages/senza/templates/webapp.py", line 77, in gather_user_variables
    rules_missing = check_security_group(sg_name + '-lb', [('tcp', 443)], region)
  File "/usr/local/lib/python3.4/site-packages/senza/templates/_helper.py", line 45, in check_security_group
    sg.add_tags({'Name': sg_name})
  File "/usr/local/lib/python3.4/site-packages/boto/ec2/ec2object.py", line 97, in add_tags
    dry_run=dry_run
  File "/usr/local/lib/python3.4/site-packages/boto/ec2/connection.py", line 4203, in create_tags
    return self.get_status('CreateTags', params, verb='POST')
  File "/usr/local/lib/python3.4/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'sg-5d023b38' does not exist</Message></Error></Errors><RequestID>...</RequestID></Response>
```

**Comment by hjacobs** [comment]
OMG the hell of async AWS processes..
We see the same problems with IAM roles, but I never experienced it (yet) with security groups..

**Comment by tuxlife** [comment]
we will add a retry, if this bug is very often
