### ISSUE TITLE
Sometimes "senza events -w" seems to crash with BotoServerError: 400 Bad Request

### ISSUE THREAD

**Issue by ekantola** [zalando-stups/senza#74]
Running `senza events -w` seems to sometimes crash with the following stack trace:

    Traceback (most recent call last):
      File "/usr/local/bin/senza", line 9, in <module>
        load_entry_point('stups-senza==0.65', 'console_scripts', 'senza')()
      File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 938, in main
        handle_exceptions(cli)()
      File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 223, in wrapper
        func()
      File "/usr/local/lib/python3.4/site-packages/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.4/site-packages/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.4/site-packages/click/core.py", line 991, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.4/site-packages/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.4/site-packages/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 521, in events
        events = cf.describe_stack_events(stack.stack_name)
      File "/usr/local/lib/python3.4/site-packages/boto/cloudformation/connection.py", line 580, in describe_stack_events
        StackEvent)])
      File "/usr/local/lib/python3.4/site-packages/boto/connection.py", line 1186, in get_list
        raise self.ResponseError(response.status, response.reason, body)
    boto.exception.BotoServerError: BotoServerError: 400 Bad Request
    <ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
      <Error>
        <Type>Sender</Type>
        <Code>Throttling</Code>
        <Message>Rate exceeded</Message>
      </Error>
      <RequestId>d7a8ef15-2c70-11e5-a49b-87ddc69fdc5a</RequestId>
    </ErrorResponse>

I don't have much more details, except that the last event from CloudFormation to the console before crash was:

    applicationname         1    AutoScaling::AutoScalingGroup      AppServer                CREATE_IN_PROGRESS Resource creation Initiated                         64s ago

and the next one (from AWS web console) was:

    CREATE_FAILED 	AWS::AutoScaling::AutoScalingGroup 	AppServer 	Failed to receive 1 resource signal(s) within the specified duration

**Comment by hjacobs** [comment]
You hit the AWS API calls rate limit :-)

**Comment by ekantola** [comment]
So this is happening with default settings. Would it be reasonable/possible to have defaults configured so that the rate limiting doesn't happen in, say, two minutes of running `senza events -w`?

**Comment by hjacobs** [comment]
There are magic/unknown API request rate limits enforced by AWS, see http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate
The limits are AFAIK per AWS account, so your team might hit limits depending on what you do..

**Comment by marek-obuchowicz** [comment]
This is pretty common problem with AWS API... Some projects (e.g. salt-cloud) have a build-in mechanism for handling this problem - if "throttling" error is received, it sleeps some seconds then repeat the request (increasing the sleep duration between each request try, as suggested by amazon docs)

**Comment by tuxlife** [comment]
i migrate senza to boto3. this has a internal retry for rate limits (or its only slower as boto :stuck_out_tongue_winking_eye:)

see #59

**Comment by tuxlife** [comment]
fixed with release 0.80
