### ISSUE TITLE
Cannot specify image

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/senza#89]
Relevant part of senza file:

~~~
- AppServer:
      Type: Senza::TaupageAutoScalingGroup
      Image: "ami-asdfasdf"
      InstanceType: t2.micro
~~~

Image definitely exists under this ID.

Error:

~~~
 EXCEPTION OCCURRED: BotoServerError: 400 Bad Request
{"Error":{"Code":"ValidationError","Message":"Template error: Unable to get mapping for Images::eu-west-1::ami-asdfasdf","Type":"Sender"},"RequestId":"xxx"}
Traceback (most recent call last):
  File "/usr/local/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 978, in main
    handle_exceptions(cli)()
  File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 223, in wrapper
    func()
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/senza/cli.py", line 451, in create
    notification_arns=topics, disable_rollback=disable_rollback, capabilities=capabilities)
  File "/usr/local/lib/python3.4/site-packages/boto/cloudformation/connection.py", line 403, in create_stack
    body = self._do_request('CreateStack', params, '/', 'POST')
  File "/usr/local/lib/python3.4/site-packages/boto/cloudformation/connection.py", line 304, in _do_request
    raise self.ResponseError(response.status, response.reason, body=body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
{"Error":{"Code":"ValidationError","Message":"Template error: Unable to get mapping for Images::eu-west-1::ami-asdfasdf","Type":"Sender"},"RequestId":"xxx"}
~~~

**Comment by hjacobs** [comment]
You have to define the image in mappings first.

**Comment by prayerslayer** [comment]
Yup, for everyone after me:

~~~
Mappings:
  Images:
    eu-west-1:
      AnImage: "ami-asdfasdf"
~~~

~~~
- AppServer:
      Type: Senza::TaupageAutoScalingGroup
      Image: AnImage
      InstanceType: t2.micro
~~~

**Comment by hjacobs** [comment]
@prayerslayer could you add this to docs.stups.io?

**Comment by prayerslayer** [comment]
Done.
